name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - run: |
          python -m pip install uv
          uv venv --python=${{ matrix.python-version }}
          uv pip install -e . pytest
          uv run pytest tests/
