name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - run: python -m pip install uv
      - run: python -m pip install -e .
      - run: python -m pytest tests/
