name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - run: |
          python -m pip install uv
          uv venv
          uv pip install -e . pytest
          uv run pytest tests/
