name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - run: python -m pip install uv
      - run: uv venv
      - run: uv pip install -e . pytest
      - run: uv run pytest tests/
